### ISSUE TITLE
how to design a language,need study what?

### ISSUE THREAD

**Issue by MDZ2** [kulics/lite#12]

**Comment by kulics** [comment]
@MDZ2 
Designing a language only requires you to have a continuous interest.

You can start designing the grammar you want right away, then code it and summarize its features until it matures.

Developing a language requires learning something.
1. The most basic need to read the books related to the compilation principle.
2. Learn to use modern tools like antlr to help parse your language.
3. Output the code to an environment that can be executed. In the early days, it can be a language such as c or java. Later, you can consider exporting to a lower-level environment.
4. Communicate more with people!
5. Continue with the above steps until it works.
