### ISSUE TITLE
fails to run demo

### ISSUE THREAD

**Issue by ledao** [kulics/lite#13]
你好，纯属个人爱好，运行一下go版本demo，发现无法运行，请问是我有什么地方没有执行正确么？

- info:
win 10, go 1.13
- what have you done:
1. go get github.com/kulics/lite-go
2. edit demo.lite, write the demo code as blow
```
"Demo" {
    "System"
}

Main : (->) {
    print("hello lite")
}
```
3. run lite-go (under a dir)
- expected to display
```
hello lite
```
- it displays
```
demo.lite
panic: interface conversion: interface is nil, not antlr.ParseTree

goroutine 1 [running]:
github.com/kulics/lite-go/visitor.(*LiteVisitor).VisitNamespaceSupportStatement(0xc0000ad650, 0xc0011631c0, 0xc0000ad650, 0x57a8cd0)
        C:/Users/davezhao.WEBANK/go/src/github.com/kulics/lite-go/visitor/namespace.go:73 +0x63
github.com/kulics/lite-go/parser/generate.(*NamespaceSupportStatementContext).Accept(0xc0011631c0, 0x774760, 0xc0000ad650, 0x57a9360, 0xc0011631c0)
        C:/Users/davezhao.WEBANK/go/src/github.com/kulics/lite-go/parser/generate/lite_parser.go:2327 +0xc3
......................etc
```

**Comment by kulics** [comment]
@ledao 你好，这里面的确有点小问题，可能需要我做一些解释。
lite目前主要是翻译成目标语言来执行的，所以还离不开目标语言的库。
1. System 不是go里面的有效仓库，所以这里不应该导入这个，可以直接用go的库 “fmt”，与此同时下面的print方法也需要使用fmt.print。
2. go里面执行main方法需要使用main包名，所以这里也得把Demo改成main。同时下面的Main方法也得改成main。
3. lite里面语句换行或者分号是必选其一的，所以文档末尾最好加一个换行，demo里的main函数结尾要么使用换行要么加个分号，否则编译不过。lite-go的错误信息部分还没完善，所以错误提示还很薄弱，有待改进。

**Comment by ledao** [comment]
改成下面这样的代码后正常运行，多谢指导！
```
"main" {
    "fmt"
}

main : (->) {
    fmt.Println("hello lite")
}

```
挺有意思的lite。

**Comment by kulics** [comment]
@ledao 写完lite我也觉得挺有意思的
